#pragma once

template <class T>
class CProxy_IPCQNGEvents : public IConnectionPointImpl<T, &__uuidof(_IPCQNGEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
